# -*- coding: utf-8 -*-
"""Copy of Naan Mudhalvan Project 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oveNAI2b1HySqoUC7PluqvDg2j_8ztwT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("Synthetic_air_quality_data.csv")
print(df.head())
print(df.isnull().sum())
df.fillna(df.median(), inplace=True)
features = ['TEMPERATURE', 'HUMIDITY', 'CO', 'NO2', 'SO2', 'PM10', 'O3']
target = 'PM2.5'
X = df[features]
y = df[target]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
model = RandomForestRegressor(n_estimators=100, random_state=52)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-Squared (R2): {r2}")
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, color='blue')
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')
plt.title('Actual vs Predicted Air Quality (PM2.5)')
plt.xlabel('Actual PM2.5')
plt.ylabel('Predicted PM2.5')
plt.show()
importance = model.feature_importances_
feature_importance_df = pd.DataFrame({
    'Feature': features,
    'Importance': importance
})
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df)
plt.title('Feature Importance in Predicting Air Quality')
plt.show()

